-- ═══════════════════════════════════════════════════════════
-- Supabase Database Setup for Premium Rentals App
-- Run this SQL in your Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════

-- ─── CRANES TABLE ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cranes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  capacity TEXT,
  price_per_hour NUMERIC NOT NULL,
  location TEXT,
  description TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  availability_status TEXT DEFAULT 'available',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ─── TRUCKS TABLE ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.trucks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  tonnage TEXT,
  capacity TEXT,
  price_per_hour NUMERIC NOT NULL,
  location TEXT,
  description TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  availability_status TEXT DEFAULT 'available',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ─── CRANE BOOKINGS TABLE ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crane_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id TEXT UNIQUE NOT NULL,
  crane_id BIGINT REFERENCES public.cranes(id) ON DELETE SET NULL,
  user_name TEXT NOT NULL,
  user_phone TEXT NOT NULL,
  booking_date DATE NOT NULL,
  start_time TEXT NOT NULL,
  duration_hours INTEGER NOT NULL,
  site_location TEXT NOT NULL,
  is_emergency BOOLEAN DEFAULT FALSE,
  total_price NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ─── TRUCK BOOKINGS TABLE ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.truck_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id TEXT UNIQUE NOT NULL,
  truck_id BIGINT REFERENCES public.trucks(id) ON DELETE SET NULL,
  user_name TEXT NOT NULL,
  user_phone TEXT NOT NULL,
  booking_date DATE NOT NULL,
  start_time TEXT NOT NULL,
  duration_hours INTEGER NOT NULL,
  site_location TEXT NOT NULL,
  is_emergency BOOLEAN DEFAULT FALSE,
  total_price NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ─── INDEXES ─────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_cranes_availability ON public.cranes(availability_status);
CREATE INDEX IF NOT EXISTS idx_cranes_location ON public.cranes(location);
CREATE INDEX IF NOT EXISTS idx_trucks_availability ON public.trucks(availability_status);
CREATE INDEX IF NOT EXISTS idx_trucks_location ON public.trucks(location);
CREATE INDEX IF NOT EXISTS idx_crane_bookings_crane_id ON public.crane_bookings(crane_id);
CREATE INDEX IF NOT EXISTS idx_crane_bookings_status ON public.crane_bookings(status);
CREATE INDEX IF NOT EXISTS idx_crane_bookings_phone ON public.crane_bookings(user_phone);
CREATE INDEX IF NOT EXISTS idx_truck_bookings_truck_id ON public.truck_bookings(truck_id);
CREATE INDEX IF NOT EXISTS idx_truck_bookings_status ON public.truck_bookings(status);
CREATE INDEX IF NOT EXISTS idx_truck_bookings_phone ON public.truck_bookings(user_phone);

-- ─── ROW LEVEL SECURITY ─────────────────────────────────
ALTER TABLE public.cranes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trucks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crane_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.truck_bookings ENABLE ROW LEVEL SECURITY;

-- Cranes policies
DROP POLICY IF EXISTS "Allow all access to cranes" ON public.cranes;
CREATE POLICY "Allow all access to cranes" ON public.cranes FOR ALL USING (true) WITH CHECK (true);

-- Trucks policies
DROP POLICY IF EXISTS "Allow all access to trucks" ON public.trucks;
CREATE POLICY "Allow all access to trucks" ON public.trucks FOR ALL USING (true) WITH CHECK (true);

-- Crane bookings policies
DROP POLICY IF EXISTS "Allow all access to crane_bookings" ON public.crane_bookings;
CREATE POLICY "Allow all access to crane_bookings" ON public.crane_bookings FOR ALL USING (true) WITH CHECK (true);

-- Truck bookings policies
DROP POLICY IF EXISTS "Allow all access to truck_bookings" ON public.truck_bookings;
CREATE POLICY "Allow all access to truck_bookings" ON public.truck_bookings FOR ALL USING (true) WITH CHECK (true);

-- ─── SAMPLE DATA ─────────────────────────────────────────

-- Sample Cranes
INSERT INTO public.cranes (name, capacity, price_per_hour, location, description, availability_status)
VALUES
  ('Hydraulic Mobile Crane 14T', '14T', 1500, 'Mumbai Depot', 'Versatile hydraulic mobile crane suitable for medium construction projects', 'available'),
  ('Tower Crane 25T', '25T', 3500, 'Pune Yard', 'High-capacity tower crane for large-scale construction', 'available'),
  ('Crawler Crane 50T', '50T', 5000, 'Thane Hub', 'Heavy-duty crawler crane for industrial lifting', 'available'),
  ('Mini Crane 5T', '5T', 800, 'Andheri Yard', 'Compact crane for tight spaces and light lifting', 'available')
ON CONFLICT DO NOTHING;

-- Sample Trucks
INSERT INTO public.trucks (name, tonnage, price_per_hour, location, description, availability_status)
VALUES
  ('Tata Prima 2528 Tipper', '25T', 2500, 'Mumbai Depot', 'Heavy duty tipper for construction materials', 'available'),
  ('Ashok Leyland 2518', '18T', 2000, 'Delhi Depot', 'Reliable cargo truck for medium loads', 'available'),
  ('Mahindra Bolero Pickup', '1.5T', 800, 'Ahmedabad Depot', 'Compact pickup for small deliveries', 'available'),
  ('Eicher 20T Cargo', '20T', 1800, 'Surat Depot', 'Standard cargo truck for various loads', 'available')
ON CONFLICT DO NOTHING;