import { create } from "zustand";
import AsyncStorage from "@react-native-async-storage/async-storage";

// Translation data
const translations = {
  en: {
    // Common
    loading: "Loading...",
    search: "Search",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    add: "Add",

    // Tabs
    browse: "Browse",
    myBookings: "My Bookings",
    notifications: "Notifications",
    profile: "Profile",

    // Browse Page
    appTitle: "Premium Rentals",
    appSubtitle: "Find the perfect equipment for your project",
    searchPlaceholder: "Search by name, capacity, or location...",
    noCranesFound: "No cranes found matching your search",
    noCranesAvailable: "No cranes available",
    loadingCranes: "Loading cranes...",
    // Truck translations (Hindi)
    trucks: "ट्रक",
    cranes: "क्रेन",
    noTrucksFound: "No trucks found matching your search",
    noTrucksAvailable: "No trucks available",
    loadingTrucks: "Loading trucks...",
    searchTruckPlaceholder: "Search by name, tonnage, or location...",
    findPerfectTruck: "Find the perfect truck for your needs",
    truckNotFound: "Truck not found",
    truckDetails: "Truck Details",
    bookTruck: "Book Truck",
    perHour: "per hour",
    availableNow: "Available Now",

    // Crane Details
    rentalRate: "Rental Rate",
    description: "Description",
    features: "Features",
    professionalOperators: "Professional operators available",
    regularMaintenance: "Regular maintenance and safety checks",
    support247: "24/7 support available",
    emergencyBooking: "Emergency booking available",
    availableForBooking: "Available for Booking",
    bookNow: "Book Now",
    craneNotFound: "Crane not found",

    // Booking Form
    bookCrane: "Book",
    personalInformation: "Personal Information",
    fullName: "Full Name",
    enterName: "Enter your name",
    phoneNumber: "Phone Number",
    enterPhone: "Enter your phone number",
    bookingDetails: "Booking Details",
    date: "Date (YYYY-MM-DD)",
    datePlaceholder: "2026-03-15",
    startTime: "Start Time (HH:MM)",
    timePlaceholder: "09:00",
    duration: "Duration (hours)",
    durationPlaceholder: "8",
    siteLocation: "Site Location",
    siteLocationPlaceholder: "Enter construction site address",
    emergencyBookingLabel: "Emergency Booking",
    emergencySurcharge: "+50% surcharge for urgent requests",
    priceSummary: "Price Summary",
    emergencySurchargeLabel: "Emergency surcharge (50%)",
    total: "Total",
    confirmBooking: "Confirm Booking",
    missingInformation: "Missing Information",
    fillAllFields: "Please fill in all fields",
    bookingSuccessful: "Booking Successful!",
    bookingIdIs: "Your booking ID is",
    statusPending: "Status: Pending Approval",
    sendWhatsApp: "Send WhatsApp",
    viewBookings: "View Bookings",
    bookingFailed: "Booking Failed",

    // My Bookings
    trackBookings: "Track your crane rental bookings",
    enterPhoneToView: "Enter your phone number to view bookings",
    enterPhoneNumber: "Enter phone number",
    bookingId: "Booking ID",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    completed: "Completed",
    cancelled: "Cancelled",
    noBookingsFound: "No bookings found for this phone number",
    enterPhonePrompt: "Enter your phone number to view your bookings",

    // Notifications
    stayUpdated: "Stay updated on your bookings",
    noNotifications: "No notifications yet",
    notificationPrompt: "You'll receive updates about your bookings here",
    welcomeTitle: "Welcome to Premium Crane Rentals!",
    welcomeMessage:
      "Book your first crane and get instant confirmation. We're here to help 24/7!",
    justNow: "Just now",

    // Profile/Settings
    settings: "Settings",
    accountSettings: "Account settings and preferences",
    contactInformation: "Contact Information",
    email: "Email",
    phone: "Phone",
    language: "Language",
    selectLanguage: "Select Language",
    english: "English",
    hindi: "हिंदी (Hindi)",
    tamil: "தமிழ் (Tamil)",
    bengali: "বাংলা (Bengali)",
    gujarati: "ગુજરાતી",
    comingSoon: "More Features Coming Soon!",
    comingSoonMessage:
      "We're working hard to bring you more amazing features. Stay tuned!",
    addYourCrane: "Want to Add Your Crane?",
    contactUs: "Contact us to add your crane to our premium fleet",
    logout: "Logout",

    // Admin
    adminPanel: "Admin Panel",
    dashboard: "Dashboard",
    manageCranes: "Manage Cranes",
    manageVehicles: "Manage Vehicles",
    totalBookings: "Total Bookings",
    pendingBookings: "Pending",
    totalRevenue: "Total Revenue",
    availableCranes: "Available Cranes",
    availableTrucks: "Available Trucks",
    manageTrucks: "Manage Trucks",
    trucksInFleet: "trucks in fleet",
    addNewTruck: "Add New Truck",
    truckName: "Truck Name",
    tonnage: "Tonnage",
    truckAddedSuccessfully: "Truck added successfully",
    truckDeletedSuccessfully: "Truck deleted successfully",
    truckNamePlaceholder: "e.g., Heavy Duty Tipper Truck",
    tonnagePlaceholder: "e.g., 25T",
    noTrucksAddedYet: "No trucks added yet",
    approve: "Approve",
    reject: "Reject",

    // Auth
    login: "Login",
    signIn: "Sign In",
    welcomeBack: "Welcome back!",
    enterCredentials: "Enter your credentials to continue",
    emailAddress: "Email Address",
    password: "Password",
    enterPassword: "Enter password",
    confirmPassword: "Confirm Password",
    reEnterPassword: "Re-enter password",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    alreadyHaveAccount: "Already have an account?",
    createAccount: "Create Account",
    joinUs: "Join us to start booking cranes & trucks",
    registerPrompt: "Create your account to start booking cranes",
    useOtpInstead: "Use OTP instead",
    usePasswordInstead: "Use password instead",
    sendOtp: "Send OTP",
    accountCreated: "Account Created",
    checkEmailToConfirm: "Check your email to confirm your account, then sign in.",
    passwordMinLength: "Password must be at least 6 characters",
    passwordMismatch: "Passwords do not match",
    loginSuccess: "Login Successful",
    loginFailed: "Login Failed",
    invalidCredentials: "Invalid credentials",
  },

  hi: {
    // Common
    loading: "लोड हो रहा है...",
    search: "खोजें",
    submit: "जमा करें",
    cancel: "रद्द करें",
    save: "सहेजें",
    delete: "हटाएं",
    edit: "संपादित करें",
    add: "जोड़ें",

    // Tabs
    browse: "ब्राउज़",
    myBookings: "मेरी बुकिंग",
    notifications: "सूचनाएं",
    profile: "प्रोफ़ाइल",

    // Browse Page
    appTitle: "प्रीमियम रेंटल",
    appSubtitle: "अपने प्रोजेक्ट के लिए सही उपकरण खोजें",
    searchPlaceholder: "नाम, क्षमता या स्थान से खोजें...",
    noCranesFound: "खोज से मेल खाने वाली कोई क्रेन नहीं मिली",
    noCranesAvailable: "कोई क्रेन उपलब्ध नहीं है",
    loadingCranes: "क्रेन लोड हो रही हैं...",
    // Truck translations Hindi
    trucks: "ट्रक",
    cranes: "क्रेन",
    noTrucksFound: "खोज से मेल खाने वाला कोई ट्रक नहीं मिला",
    noTrucksAvailable: "कोई ट्रक उपलब्ध नहीं है",
    loadingTrucks: "ट्रक लोड हो रहे हैं...",
    searchTruckPlaceholder: "नाम, टन या स्थान से खोजें...",
    findPerfectTruck: "अपनी जरूरतों के लिए सही ट्रक खोजें",
    truckNotFound: "ट्रक नहीं मिला",
    truckDetails: "ट्रक विवरण",
    bookTruck: "ट्रक बुक करें",
    perHour: "प्रति घंटा",
    availableNow: "अभी उपलब्ध",

    // Crane Details
    rentalRate: "किराया दर",
    description: "विवरण",
    features: "विशेषताएं",
    professionalOperators: "पेशेवर ऑपरेटर उपलब्ध",
    regularMaintenance: "नियमित रखरखाव और सुरक्षा जांच",
    support247: "24/7 सहायता उपलब्ध",
    emergencyBooking: "आपातकालीन बुकिंग उपलब्ध",
    availableForBooking: "बुकिंग के लिए उपलब्ध",
    bookNow: "अभी बुक करें",
    craneNotFound: "क्रेन नहीं मिली",

    // Booking Form
    bookCrane: "बुक करें",
    personalInformation: "व्यक्तिगत जानकारी",
    fullName: "पूरा नाम",
    enterName: "अपना नाम दर्ज करें",
    phoneNumber: "फोन नंबर",
    enterPhone: "अपना फोन नंबर दर्ज करें",
    bookingDetails: "बुकिंग विवरण",
    date: "तारीख (YYYY-MM-DD)",
    datePlaceholder: "2026-03-15",
    startTime: "शुरू का समय (HH:MM)",
    timePlaceholder: "09:00",
    duration: "अवधि (घंटे)",
    durationPlaceholder: "8",
    siteLocation: "साइट का स्थान",
    siteLocationPlaceholder: "निर्माण स्थल का पता दर्ज करें",
    emergencyBookingLabel: "आपातकालीन बुकिंग",
    emergencySurcharge: "तत्काल अनुरोधों के लिए +50% अधिभार",
    priceSummary: "मूल्य सारांश",
    emergencySurchargeLabel: "आपातकालीन अधिभार (50%)",
    total: "कुल",
    confirmBooking: "बुकिंग की पुष्टि करें",
    missingInformation: "जानकारी गायब है",
    fillAllFields: "कृपया सभी फ़ील्ड भरें",
    bookingSuccessful: "बुकिंग सफल!",
    bookingIdIs: "आपकी बुकिंग ID है",
    statusPending: "स्थिति: अनुमोदन लंबित",
    sendWhatsApp: "WhatsApp भेजें",
    viewBookings: "बुकिंग देखें",
    bookingFailed: "बुकिंग विफल",

    // My Bookings
    trackBookings: "अपनी क्रेन किराया बुकिंग ट्रैक करें",
    enterPhoneToView: "बुकिंग देखने के लिए अपना फोन नंबर दर्ज करें",
    enterPhoneNumber: "फोन नंबर दर्ज करें",
    bookingId: "बुकिंग ID",
    pending: "लंबित",
    approved: "स्वीकृत",
    rejected: "अस्वीकृत",
    completed: "पूर्ण",
    cancelled: "रद्द",
    noBookingsFound: "इस फोन नंबर के लिए कोई बुकिंग नहीं मिली",
    enterPhonePrompt: "अपनी बुकिंग देखने के लिए अपना फोन नंबर दर्ज करें",

    // Notifications
    stayUpdated: "अपनी बुकिंग पर अपडेट रहें",
    noNotifications: "अभी तक कोई सूचना नहीं",
    notificationPrompt: "आपको यहां अपनी बुकिंग के बारे में अपडेट मिलेगा",
    welcomeTitle: "प्रीमियम क्रेन रेंटल में आपका स्वागत है!",
    welcomeMessage:
      "अपनी पहली क्रेन बुक करें और तुरंत पुष्टि प्राप्त करें। हम 24/7 मदद के लिए यहां हैं!",
    justNow: "अभी",

    // Profile/Settings
    settings: "सेटिंग्स",
    accountSettings: "खाता सेटिंग्स और प्राथमिकताएं",
    contactInformation: "संपर्क जानकारी",
    email: "ईमेल",
    phone: "फोन",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
    english: "English (अंग्रेजी)",
    hindi: "हिंदी",
    tamil: "தமிழ் (तमिल)",
    bengali: "বাংলা (बंगाली)",
    comingSoon: "जल्द आ रहे हैं और फीचर्स!",
    comingSoonMessage:
      "हम आपके लिए और शानदार फीचर्स लाने के लिए कड़ी मेहनत कर रहे हैं। बने रहें!",
    addYourCrane: "अपनी क्रेन जोड़ना चाहते हैं?",
    contactUs: "अपनी क्रेन को हमारे प्रीमियम फ्लीट में जोड़ने के लिए हमसे संपर्क करें",
    logout: "लॉगआउट",

    // Admin
    adminPanel: "एडमिन पैनल",
    dashboard: "डैशबोर्ड",
    manageCranes: "क्रेन प्रबंधित करें",
    manageVehicles: "वाहन प्रबंधित करें",
    totalBookings: "कुल बुकिंग",
    pendingBookings: "लंबित",
    totalRevenue: "कुल राजस्व",
    availableCranes: "उपलब्ध क्रेन",
    availableTrucks: "उपलब्ध ट्रक",
    manageTrucks: "ट्रक प्रबंधित करें",
    trucksInFleet: "फ्लीट में ट्रक",
    addNewTruck: "नया ट्रक जोड़ें",
    truckName: "ट्रक का नाम",
    tonnage: "टन क्षमता",
    truckAddedSuccessfully: "ट्रक सफलतापूर्वक जोड़ा गया",
    truckDeletedSuccessfully: "ट्रक सफलतापूर्वक हटाया गया",
    truckNamePlaceholder: "e.g., हैवी ड्यूटी टिपर ट्रक",
    tonnagePlaceholder: "e.g., 25T",
    noTrucksAddedYet: "अभी तक कोई ट्रक नहीं जोड़ा गया",
    approve: "स्वीकृत करें",
    reject: "अस्वीकार करें",

    // Auth
    login: "लॉगिन",
    signIn: "साइन इन करें",
    welcomeBack: "वापसी पर स्वागत है!",
    enterCredentials: "जारी रखने के लिए अपनी जानकारी दर्ज करें",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    enterPassword: "पासवर्ड दर्ज करें",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    reEnterPassword: "पासवर्ड फिर से दर्ज करें",
    forgotPassword: "पासवर्ड भूल गए?",
    dontHaveAccount: "खाता नहीं है?",
    signUp: "साइन अप करें",
    alreadyHaveAccount: "पहले से खाता है?",
    createAccount: "खाता बनाएं",
    joinUs: "क्रेन और ट्रक बुक करने के लिए हमसे जुड़ें",
    registerPrompt: "क्रेन बुक करना शुरू करने के लिए अपना खाता बनाएं",
    useOtpInstead: "इसके बजाय OTP का उपयोग करें",
    usePasswordInstead: "इसके बजाय पासवर्ड का उपयोग करें",
    sendOtp: "OTP भेजें",
    accountCreated: "खाता बनाया गया",
    checkEmailToConfirm: "अपने खाते की पुष्टि करने के लिए अपना ईमेल जांचें, फिर साइन इन करें।",
    passwordMinLength: "पासवर्ड कम से कम 6 अक्षर का होना चाहिए",
    passwordMismatch: "पासवर्ड मेल नहीं खाते",
    loginSuccess: "लॉगिन सफल",
    loginFailed: "लॉगिन विफल",
    invalidCredentials: "अमान्य क्रेडेंशियल",
  },

  gu: {
    // Common
    loading: "લોડ થઈ રહ્યું છે...",
    search: "શોધો",
    submit: "સબમિટ",
    cancel: "રદ કરો",
    save: "સેવ",
    delete: "દૂર કરો",
    edit: "સંપાદન",
    add: "ઉમેરો",

    // Tabs
    browse: "બ્રાઉઝ",
    myBookings: "મારી બુકિંગ",
    notifications: "સૂચનાઓ",
    profile: "પ્રોફાઈલ",

    // Browse Page
    appTitle: "પ્રિમિયમ રેન્ટલ્સ",
    appSubtitle: "તમારી પ્રોજેક્ટ માટે યોગ્ય ઉપકરણ શોધો",
    searchPlaceholder: "નામ, ક્ષમતા અથવા સ્થાન દ્વારા શોધો...",
    noCranesFound: "તમારી શોધ સાથે મેળ ખાતી કોઈ ક્રેન મળી નથી",
    noCranesAvailable: "કોઈ ક્રેન ઉપલબ્ધ નથી",
    loadingCranes: "ક્રેન લોડ થઈ રહી છે...",
    // Truck translations Gujarati
    trucks: "ટ્રક",
    cranes: "ક્રેન",
    noTrucksFound: "તમારી શોધ સાથે મેળ ખાતો કોઈ ટ્રક મળ્યો નથી",
    noTrucksAvailable: "કોઈ ટ્રક ઉપલબ્ધ નથી",
    loadingTrucks: "ટ્રક લોડ થઈ રહ્યા છે...",
    searchTruckPlaceholder: "નામ, ટન અથવા સ્થાન દ્વારા શોધો...",
    findPerfectTruck: "તમારી જરૂરિયાતો માટે યોગ્ય ટ્રક શોધો",
    truckNotFound: "ટ્રક મળ્યો નથી",
    truckDetails: "ટ્રક વિગતો",
    bookTruck: "ટ્રક બુક કરો",
    perHour: "પ્રતિ કલાક",
    availableNow: "હવે ઉપલબ્ધ",

    // Crane Details
    rentalRate: "ભાડુઆત",
    description: "વર્ણન",
    features: "સુવિધાઓ",
    professionalOperators: "વ્યાવસાયિક ઓપરેટર ઉપલબ્ધ",
    regularMaintenance: "નિયમિત જામન અને સુરક્ષા તપાસ",
    support247: "24/7 સહાય ઉપલબ્ધ",
    emergencyBooking: "આપત્તિ બુકિંગ ઉપલબ્ધ",
    availableForBooking: "બુકિંગ માટે ઉપલબ્ધ",
    bookNow: "હવે બુક કરો",
    craneNotFound: "ક્રેન મળી નથી",

    // Booking Form
    bookCrane: "બુક",
    personalInformation: "વ્યક્તિગત માહિતી",
    fullName: "પૂરું નામ",
    enterName: "તમારું નામ દાખલ કરો",
    phoneNumber: "ફોન નંબર",
    enterPhone: "તમારો ફોન નંબર દાખલ કરો",
    bookingDetails: "બુકિંગ વિગતો",
    date: "તારીખ (YYYY-MM-DD)",
    datePlaceholder: "2026-03-15",
    startTime: "શરૂ સમય (HH:MM)",
    timePlaceholder: "09:00",
    duration: "સમયગાળો (કલાક)",
    durationPlaceholder: "8",
    siteLocation: "સાઇટ સ્થાન",
    siteLocationPlaceholder: "બાંધણી સાઇટનું સરનામું દાખલ કરો",
    emergencyBookingLabel: "આપત્તિ બુકિંગ",
    emergencySurcharge: "તાત્કાલિક વિનંતીઓ માટે +50% સરચાર્જ",
    priceSummary: "ભાવ સારાંશ",
    emergencySurchargeLabel: "આપત્તિ સરચાર્જ (50%)",
    total: "કુલ",
    confirmBooking: "બુકિંગ પુષ્ટિ કરો",
    missingInformation: "માહિતી ગુમ છે",
    fillAllFields: "કૃપા કરીને બધા ફીલ્ડ ભરો",
    bookingSuccessful: "બુકિંગ સફળ!",
    bookingIdIs: "તમારી બુકિંગ ID છે",
    statusPending: "સ્થિતિ: મંજૂરી બાકી",
    sendWhatsApp: "WhatsApp મોકલો",
    viewBookings: "બુકિંગ જુઓ",
    bookingFailed: "બુકિંગ નિષ્ફળ",

    // My Bookings
    trackBookings: "તમારી ક્રેન ભાડાની બુકિંગ ટ્રૅક કરો",
    enterPhoneToView: "બુકિંગ જોવા માટે તમારો ફોન નંબર દાખલ કરો",
    enterPhoneNumber: "ફોન નંબર દાખલ કરો",
    bookingId: "બુકિંગ ID",
    pending: "બાકી",
    approved: "મંજૂર",
    rejected: "નામંજૂર",
    completed: "પૂર્ણ",
    cancelled: "રદ",
    noBookingsFound: "આ ફોન નંબર માટે કોઈ બુકિંગ મળી નથી",
    enterPhonePrompt: "તમારી બુકિંગ જોવા માટે તમારો ફોન નંબર દાખલ કરો",

    // Notifications
    stayUpdated: "તમારી બુકિંગ પર અપડેટેડ રહો",
    noNotifications: "હજુ સુધી કોઈ સૂચના નથી",
    notificationPrompt: "તમને અહીં તમારી બુકિંગ વિશે અપડેટ મળશે",
    welcomeTitle: "પ્રિમિયમ ક્રેન રેન્ટલ્સમાં સ્વાગત છે!",
    welcomeMessage:
      "તમારી પ્રથમ ક્રેન બુક કરો અને તુરંત પુષ્ટિ મેળવો. અમે 24/7 મદદ માટે અહીં છીએ!",
    justNow: "હવે",

    // Profile/Settings
    settings: "સેટિંગ્સ",
    accountSettings: "ખાતું સેટિંગ્સ અને પસંદગીઓ",
    contactInformation: "સંપર્ક માહિતી",
    email: "ઈમેલ",
    phone: "ફોન",
    language: "ભાષા",
    selectLanguage: "ભાષા પસંદ કરો",
    english: "English (અંગ્રેજી)",
    hindi: "हिंदી (હિન્દી)",
    tamil: "தமிழ் (તમિલ)",
    bengali: "বাংলা (બંગાલી)",
    gujarati: "ગુજરાતી",
    comingSoon: "વધુ સુવિધાઓ જલ્દી આવી રહ્યા છે!",
    comingSoonMessage:
      "અમે તમારા માટે વધુ સરસ સુવિધાઓ લાવવા માટે સખત મહેનત કરી રહ્યા છીએ. રાહ જુઓ!",
    addYourCrane: "તમારી ક્રેન ઉમેરવા છો?",
    contactUs: "તમારી ક્રેન અમારી પ્રિમિયમ ફ્લીટમાં ઉમેરવા માટે અમારો સંપર્ક કરો",
    logout: "લૉગઆઉટ",

    // Admin
    adminPanel: "એડમિન પૅનલ",
    dashboard: "ડૅશબોર્ડ",
    manageCranes: "ક્રેન મેનેજ કરો",
    manageVehicles: "વાહનો મેનેજ કરો",
    totalBookings: "કુલ બુકિંગ",
    pendingBookings: "બાકી",
    totalRevenue: "કુલ આવક",
    availableCranes: "ઉપલબ્ધ ક્રેન",
    availableTrucks: "ઉપલબ્ધ ટ્રક",
    manageTrucks: "ટ્રક મેનેજ કરો",
    trucksInFleet: "ફ્લીટમાં ટ્રક",
    addNewTruck: "નવો ટ્રક ઉમેરો",
    truckName: "ટ્રક નામ",
    tonnage: "ટન",
    truckAddedSuccessfully: "ટ્રક સફળતાપૂર્ણપણે ઉમેરવામાં આવ્યો",
    truckDeletedSuccessfully: "ટ્રક સફળતાપૂર્ણપણે દૂર કરવામાં આવ્યો",
    truckNamePlaceholder: "e.g., હેવી ડ્યુટી ટિપર ટ્રક",
    tonnagePlaceholder: "e.g., 25T",
    noTrucksAddedYet: "હજુ સુધી કોઈ ટ્રક ઉમેરવામાં આવ્યો નથી",
    approve: "મંજૂર કરો",
    reject: "નામંજૂર કરો",

    // Auth
    login: "લૉગિન",
    signIn: "સાઇન ઇન",
    welcomeBack: "પાછા સ્વાગત છે!",
    enterCredentials: "ચાલુ રાખવા માટે તમારી માહિતી દાખલ કરો",
    emailAddress: "ઈમેલ સરનામું",
    password: "પાસવર્ડ",
    enterPassword: "પાસવર્ડ દાખલ કરો",
    confirmPassword: "પાસવર્ડની પુષ્ટિ કરો",
    reEnterPassword: "પાસવર્ડ ફરીથી દાખલ કરો",
    forgotPassword: "પાસવર્ડ ભૂલી ગયા?",
    dontHaveAccount: "ખાતું નથી?",
    signUp: "સાઇન અપ",
    alreadyHaveAccount: "પહેલેથી ખાતું છે?",
    createAccount: "ખાતું બનાવો",
    joinUs: "ક્રેન અને ટ્રક બુક કરવા માટે અમારી સાથે જોડાઓ",
    registerPrompt: "ક્રેન બુક કરવા શરૂ કરવા માટે તમારું ખાતું બનાવો",
    useOtpInstead: "તેના બદલે OTP નો ઉપયોગ કરો",
    usePasswordInstead: "તેના બદલે પાસવર્ડ નો ઉપયોગ કરો",
    sendOtp: "OTP મોકલો",
    accountCreated: "ખાતું બનાવ્યું",
    checkEmailToConfirm: "તમારા ખાતાની પુષ્ટિ કરવા માટે તમારો ઈમેલ તપાસો, પછી સાઇન ઇન કરો.",
    passwordMinLength: "પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરનો હોવો જોઈએ",
    passwordMismatch: "પાસવર્ડ મેળ ખાતા નથી",
    loginSuccess: "લૉગિન સફળ",
    loginFailed: "લૉગિન નિષ્ફળ",
    invalidCredentials: "અમાન્ય ક્રેડેન્શિયલ",
  },
};

// Language store
export const useLanguageStore = create((set) => ({
  currentLanguage: "en",
  setLanguage: async (lang) => {
    set({ currentLanguage: lang });
    await AsyncStorage.setItem("app_language", lang);
  },
  loadLanguage: async () => {
    const savedLang = await AsyncStorage.getItem("app_language");
    if (savedLang) {
      set({ currentLanguage: savedLang });
    }
  },
}));

// Hook to use translations
export const useTranslation = () => {
  const currentLanguage = useLanguageStore((state) => state.currentLanguage);

  const t = (key) => {
    return (
      translations[currentLanguage]?.[key] || translations["en"][key] || key
    );
  };

  return { t, currentLanguage };
};

export default translations;
